import bcrypt from "bcrypt";

export const users = [
  {
    gender: "male",
    name: { first: "Admin", last: "User" },
    location: {
      street: { number: 123456, name: "Fullstack Inflation" },
      city: "Greymouth",
      state: "Bay of Plenty",
      country: "New Zealand",
      postcode: 35287,
    },
    email: "adming@example.com",
    login: { username: "admin", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2011-03-23T07:46:00.745Z", age: 11 },
    phone: "(491)-929-8389",
    picture: { large: "https://randomuser.me/api/portraits/men/95.jpg" },
    isAdmin: true,
  },
  {
    gender: "male",
    name: { first: "Harry", last: "Wang" },
    location: {
      street: { number: 7908, name: "Heretaunga Street" },
      city: "Greymouth",
      state: "Bay of Plenty",
      country: "New Zealand",
      postcode: 35287,
    },
    email: "harry.wang@example.com",
    login: { username: "ticklishkoala244", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2011-03-23T07:46:00.745Z", age: 11 },
    phone: "(491)-929-8389",
    picture: {
      large: "https://randomuser.me/api/portraits/men/95.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/95.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/95.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Kimaya", last: "Nair" },
    location: {
      street: { number: 20, name: "Rasta Peth" },
      city: "Tezpur",
      state: "Haryana",
      country: "India",
      postcode: 42705,
    },
    email: "kimaya.nair@example.com",
    login: { username: "crazybutterfly674", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2022-04-20T10:02:35.243Z", age: 0 },
    phone: "8915370754",
    picture: {
      large: "https://randomuser.me/api/portraits/women/39.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/39.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/39.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Keith", last: "Cole" },
    location: {
      street: { number: 9284, name: "Alexander Road" },
      city: "Cashel",
      state: "Wicklow",
      country: "Ireland",
      postcode: 95233,
    },
    email: "keith.cole@example.com",
    login: { username: "whitepeacock290", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2006-01-20T22:26:13.432Z", age: 16 },
    phone: "061-643-0605",
    picture: {
      large: "https://randomuser.me/api/portraits/men/75.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/75.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/75.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Pablo", last: "Faure" },
    location: {
      street: { number: 2795, name: "Rue du Village" },
      city: "Nancy",
      state: "Var",
      country: "France",
      postcode: 18557,
    },
    email: "pablo.faure@example.com",
    login: { username: "bigpeacock525", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2004-06-15T08:02:36.308Z", age: 18 },
    phone: "03-88-91-01-09",
    picture: {
      large: "https://randomuser.me/api/portraits/men/68.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/68.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/68.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Marsha", last: "Schmidt" },
    location: {
      street: { number: 9477, name: "Hogan St" },
      city: "Australian Capital Territory",
      state: "South Australia",
      country: "Australia",
      postcode: 9561,
    },
    email: "marsha.schmidt@example.com",
    login: { username: "lazycat823", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2021-09-20T21:24:59.194Z", age: 0 },
    phone: "03-6448-5404",
    picture: {
      large: "https://randomuser.me/api/portraits/women/39.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/39.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/39.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Predrag", last: "Stojanović" },
    location: {
      street: { number: 4877, name: "Batuska" },
      city: "Inđija",
      state: "South Bačka",
      country: "Serbia",
      postcode: 76468,
    },
    email: "predrag.stojanovic@example.com",
    login: { username: "bigleopard275", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2017-09-13T02:34:02.564Z", age: 4 },
    phone: "020-2815-097",
    picture: {
      large: "https://randomuser.me/api/portraits/men/97.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/97.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/97.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Ananya", last: "Dhamdhame" },
    location: {
      street: { number: 1539, name: "Rasta Peth" },
      city: "Amroha",
      state: "Puducherry",
      country: "India",
      postcode: 76743,
    },
    email: "ananya.dhamdhame@example.com",
    login: { username: "purplewolf825", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2021-05-26T00:41:48.096Z", age: 1 },
    phone: "7059136395",
    picture: {
      large: "https://randomuser.me/api/portraits/women/40.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/40.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/40.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Julie", last: "Poulsen" },
    location: {
      street: { number: 1867, name: "Frueløkke" },
      city: "Sommersted",
      state: "Hovedstaden",
      country: "Denmark",
      postcode: 26374,
    },
    email: "julie.poulsen@example.com",
    login: { username: "greensnake703", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2011-03-26T08:04:29.391Z", age: 11 },
    phone: "37832374",
    picture: {
      large: "https://randomuser.me/api/portraits/women/3.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/3.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/3.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Renuka", last: "Nayak" },
    location: {
      street: { number: 2910, name: "Rajaji Salai" },
      city: "Bidar",
      state: "Assam",
      country: "India",
      postcode: 53025,
    },
    email: "renuka.nayak@example.com",
    login: { username: "blackgoose897", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2015-07-21T09:07:52.778Z", age: 7 },
    phone: "9361847336",
    picture: {
      large: "https://randomuser.me/api/portraits/women/25.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/25.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/25.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Saana", last: "Ruona" },
    location: {
      street: { number: 3390, name: "Pirkankatu" },
      city: "Joutsa",
      state: "Central Finland",
      country: "Finland",
      postcode: 94531,
    },
    email: "saana.ruona@example.com",
    login: { username: "goldentiger604", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2008-12-28T22:52:14.220Z", age: 13 },
    phone: "04-299-372",
    picture: {
      large: "https://randomuser.me/api/portraits/women/55.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/55.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/55.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Adem", last: "Erbulak" },
    location: {
      street: { number: 4807, name: "Atatürk Sk" },
      city: "Batman",
      state: "Ağrı",
      country: "Turkey",
      postcode: 14833,
    },
    email: "adem.erbulak@example.com",
    login: { username: "sadelephant161", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2019-08-16T13:10:34.784Z", age: 3 },
    phone: "(715)-056-5738",
    picture: {
      large: "https://randomuser.me/api/portraits/men/8.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/8.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/8.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Johannus", last: "Van de Rijt" },
    location: {
      street: { number: 7460, name: "Karrenwiel" },
      city: "Eindhoven",
      state: "Utrecht",
      country: "Netherlands",
      postcode: 4129,
    },
    email: "johannus.vanderijt@example.com",
    login: { username: "orangewolf351", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2021-10-21T19:17:40.218Z", age: 0 },
    phone: "(059) 6309249",
    picture: {
      large: "https://randomuser.me/api/portraits/men/58.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/58.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/58.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Rayan", last: "Rey" },
    location: {
      street: { number: 7680, name: "Place Paul-Duquaire" },
      city: "Nice",
      state: "Bas-Rhin",
      country: "France",
      postcode: 46539,
    },
    email: "rayan.rey@example.com",
    login: { username: "silverbear824", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2006-05-31T02:44:48.800Z", age: 16 },
    phone: "05-31-00-83-42",
    picture: {
      large: "https://randomuser.me/api/portraits/men/63.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/63.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/63.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Nicoline", last: "Olsen" },
    location: {
      street: { number: 7409, name: "Skibhusvej" },
      city: "Pandrup",
      state: "Danmark",
      country: "Denmark",
      postcode: 25595,
    },
    email: "nicoline.olsen@example.com",
    login: { username: "goldenfish542", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2018-12-19T21:56:25.755Z", age: 3 },
    phone: "29073330",
    picture: {
      large: "https://randomuser.me/api/portraits/women/69.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/69.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/69.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Malvin", last: "Haugo" },
    location: {
      street: { number: 4026, name: "Knud Graahs gate" },
      city: "Aksdal",
      state: "Buskerud",
      country: "Norway",
      postcode: 5751,
    },
    email: "malvin.haugo@example.com",
    login: { username: "silverswan811", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2010-02-10T13:10:42.487Z", age: 12 },
    phone: "57101450",
    picture: {
      large: "https://randomuser.me/api/portraits/men/9.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/9.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/9.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Hedvig", last: "Hauge" },
    location: {
      street: { number: 85, name: "Platåveien" },
      city: "Reine",
      state: "Bergen",
      country: "Norway",
      postcode: 5853,
    },
    email: "hedvig.hauge@example.com",
    login: { username: "bluezebra682", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2002-12-01T06:30:09.540Z", age: 19 },
    phone: "55673582",
    picture: {
      large: "https://randomuser.me/api/portraits/women/18.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/18.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/18.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Nathan", last: "Hubert" },
    location: {
      street: { number: 4695, name: "Rue Dubois" },
      city: "Versailles",
      state: "Gers",
      country: "France",
      postcode: 19997,
    },
    email: "nathan.hubert@example.com",
    login: { username: "yellowlion810", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2004-10-10T03:09:54.827Z", age: 17 },
    phone: "05-24-13-37-64",
    picture: {
      large: "https://randomuser.me/api/portraits/men/80.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/80.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/80.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Frederikke", last: "Sørensen" },
    location: {
      street: { number: 979, name: "Fasanvej" },
      city: "Lemvig",
      state: "Midtjylland",
      country: "Denmark",
      postcode: 71939,
    },
    email: "frederikke.sorensen@example.com",
    login: { username: "silverleopard643", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2005-09-17T11:04:27.751Z", age: 16 },
    phone: "36932473",
    picture: {
      large: "https://randomuser.me/api/portraits/men/27.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/27.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/27.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Arnold", last: "Öz" },
    location: {
      street: { number: 7659, name: "Karelia" },
      city: "Bierum",
      state: "Utrecht",
      country: "Netherlands",
      postcode: 2443,
    },
    email: "arnold.oz@example.com",
    login: { username: "happytiger356", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2016-09-25T19:09:57.959Z", age: 5 },
    phone: "(0568) 402660",
    picture: {
      large: "https://randomuser.me/api/portraits/men/47.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/47.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/47.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Arthur", last: "Kowalski" },
    location: {
      street: { number: 9812, name: "Coastal Highway" },
      city: "Alma",
      state: "Nunavut",
      country: "Canada",
      postcode: 5343,
    },
    email: "arthur.kowalski@example.com",
    login: { username: "browngoose974", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2005-06-13T10:54:05.422Z", age: 17 },
    phone: "R59 H64-4837",
    picture: {
      large: "https://randomuser.me/api/portraits/men/22.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/22.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/22.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Stella", last: "Hellevik" },
    location: {
      street: { number: 1542, name: "Trondheimsveien" },
      city: "Nakkerud",
      state: "Trøndelag",
      country: "Norway",
      postcode: 4802,
    },
    email: "stella.hellevik@example.com",
    login: { username: "angrygoose950", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2018-03-08T23:56:11.112Z", age: 4 },
    phone: "39465312",
    picture: {
      large: "https://randomuser.me/api/portraits/women/1.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/1.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/1.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Asmee", last: "Anchan" },
    location: {
      street: { number: 3912, name: "Rasta Peth" },
      city: "Katni",
      state: "Delhi",
      country: "India",
      postcode: 92017,
    },
    email: "asmee.anchan@example.com",
    login: { username: "blackpeacock343", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2014-09-06T06:04:24.302Z", age: 7 },
    phone: "8329474708",
    picture: {
      large: "https://randomuser.me/api/portraits/women/22.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/22.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/22.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Kübra", last: "Duygulu" },
    location: {
      street: { number: 90, name: "Bağdat Cd" },
      city: "Erzurum",
      state: "Isparta",
      country: "Turkey",
      postcode: 52326,
    },
    email: "kubra.duygulu@example.com",
    login: { username: "silverdog142", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2003-10-21T16:23:58.642Z", age: 18 },
    phone: "(476)-399-5677",
    picture: {
      large: "https://randomuser.me/api/portraits/women/12.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/12.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/12.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Mileta", last: "Filipović" },
    location: {
      street: { number: 9409, name: "Bobovačka" },
      city: "Despotovac",
      state: "Rasina",
      country: "Serbia",
      postcode: 39531,
    },
    email: "mileta.filipovic@example.com",
    login: { username: "purpleelephant861", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2005-10-27T11:04:42.669Z", age: 16 },
    phone: "026-0469-057",
    picture: {
      large: "https://randomuser.me/api/portraits/men/98.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/98.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/98.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Nevio", last: "Morin" },
    location: {
      street: { number: 2065, name: "Esplanade du 9 Novembre 1989" },
      city: "Blenio",
      state: "Graubünden",
      country: "Switzerland",
      postcode: 8728,
    },
    email: "nevio.morin@example.com",
    login: { username: "silverladybug847", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2017-03-22T01:47:42.173Z", age: 5 },
    phone: "079 119 23 49",
    picture: {
      large: "https://randomuser.me/api/portraits/men/8.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/8.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/8.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Timo", last: "Dierkes" },
    location: {
      street: { number: 7700, name: "Blumenstraße" },
      city: "Freyung-Grafenau",
      state: "Rheinland-Pfalz",
      country: "Germany",
      postcode: 64041,
    },
    email: "timo.dierkes@example.com",
    login: { username: "ticklishkoala142", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2015-05-06T20:12:26.629Z", age: 7 },
    phone: "0356-8377084",
    picture: {
      large: "https://randomuser.me/api/portraits/men/10.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/10.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/10.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Soncelika", last: "Sinko" },
    location: {
      street: { number: 3992, name: "Kislovodska" },
      city: "Kicman",
      state: "Poltavska",
      country: "Ukraine",
      postcode: 33341,
    },
    email: "soncelika.sinko@example.com",
    login: { username: "sadcat571", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2007-02-28T21:26:11.386Z", age: 15 },
    phone: "(066) O84-0740",
    picture: {
      large: "https://randomuser.me/api/portraits/women/5.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/5.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/5.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Radiša", last: "Rakić" },
    location: {
      street: { number: 6220, name: "Valačka" },
      city: "Surdulica",
      state: "Zaječar",
      country: "Serbia",
      postcode: 15161,
    },
    email: "radisa.rakic@example.com",
    login: { username: "purplebird373", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2020-07-05T02:58:37.455Z", age: 2 },
    phone: "020-1147-806",
    picture: {
      large: "https://randomuser.me/api/portraits/men/96.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/96.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/96.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "ستایش", last: "سلطانی نژاد" },
    location: {
      street: { number: 498, name: "سپهبد قرنی" },
      city: "اهواز",
      state: "یزد",
      country: "Iran",
      postcode: 59186,
    },
    email: "stysh.sltnynjd@example.com",
    login: { username: "redpeacock566", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2009-06-20T04:38:51.974Z", age: 13 },
    phone: "047-03238212",
    picture: {
      large: "https://randomuser.me/api/portraits/women/68.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/68.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/68.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Marinda", last: "Heringa" },
    location: {
      street: { number: 7066, name: "Dwarshaspel" },
      city: "Koningslust",
      state: "Noord-Brabant",
      country: "Netherlands",
      postcode: 7156,
    },
    email: "marinda.heringa@example.com",
    login: { username: "sadmeercat226", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2002-12-28T04:42:38.093Z", age: 19 },
    phone: "(067) 7031605",
    picture: {
      large: "https://randomuser.me/api/portraits/women/27.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/27.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/27.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Danka", last: "Grujić" },
    location: {
      street: { number: 2364, name: "Poganovska" },
      city: "Kanjiža",
      state: "Šumadija",
      country: "Serbia",
      postcode: 25098,
    },
    email: "danka.grujic@example.com",
    login: { username: "blackfrog984", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2009-08-27T12:56:28.610Z", age: 12 },
    phone: "020-2511-445",
    picture: {
      large: "https://randomuser.me/api/portraits/women/29.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/29.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/29.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Darlene", last: "Kelley" },
    location: {
      street: { number: 9829, name: "E Sandy Lake Rd" },
      city: "West Palm Beach",
      state: "Indiana",
      country: "United States",
      postcode: 12187,
    },
    email: "darlene.kelley@example.com",
    login: { username: "beautifullion287", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2018-08-27T11:20:35.814Z", age: 3 },
    phone: "(973) 461-5151",
    picture: {
      large: "https://randomuser.me/api/portraits/women/75.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/75.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/75.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Citlali", last: "Valverde" },
    location: {
      street: { number: 3768, name: "Viaducto Sinaloa" },
      city: "Puerto San Carlos",
      state: "Jalisco",
      country: "Mexico",
      postcode: 90263,
    },
    email: "citlali.valverde@example.com",
    login: { username: "tinyleopard594", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2004-02-06T04:20:43.830Z", age: 18 },
    phone: "(636) 228 3793",
    picture: {
      large: "https://randomuser.me/api/portraits/women/85.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/85.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/85.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Villads", last: "Madsen" },
    location: {
      street: { number: 7003, name: "Tranevænget" },
      city: "Pandrup",
      state: "Hovedstaden",
      country: "Denmark",
      postcode: 19879,
    },
    email: "villads.madsen@example.com",
    login: { username: "silverlion652", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2002-11-27T13:37:40.400Z", age: 19 },
    phone: "56037591",
    picture: {
      large: "https://randomuser.me/api/portraits/men/83.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/83.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/83.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Gordomisl", last: "Lastoveckiy" },
    location: {
      street: { number: 2081, name: "Zarichanska" },
      city: "Gorohiv",
      state: "Ivano-Frankivska",
      country: "Ukraine",
      postcode: 45541,
    },
    email: "gordomisl.lastoveckiy@example.com",
    login: { username: "redbutterfly108", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2009-08-26T18:42:21.863Z", age: 12 },
    phone: "(097) E71-9602",
    picture: {
      large: "https://randomuser.me/api/portraits/men/11.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/11.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/11.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Adam", last: "Kristensen" },
    location: {
      street: { number: 9272, name: "Dalen" },
      city: "Aalborg S.Ø.",
      state: "Danmark",
      country: "Denmark",
      postcode: 20352,
    },
    email: "adam.kristensen@example.com",
    login: { username: "beautifulpanda725", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2009-12-19T11:20:16.975Z", age: 12 },
    phone: "32867762",
    picture: {
      large: "https://randomuser.me/api/portraits/men/71.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/71.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/71.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Jesse", last: "Maki" },
    location: {
      street: { number: 8705, name: "Mechelininkatu" },
      city: "Evijärvi",
      state: "Satakunta",
      country: "Finland",
      postcode: 83338,
    },
    email: "jesse.maki@example.com",
    login: { username: "goldenbear351", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2014-07-07T09:12:55.494Z", age: 8 },
    phone: "07-275-172",
    picture: {
      large: "https://randomuser.me/api/portraits/men/36.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/36.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/36.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Octaviano", last: "Lopes" },
    location: {
      street: { number: 9536, name: "Rua Belo Horizonte " },
      city: "Itu",
      state: "Rio Grande do Norte",
      country: "Brazil",
      postcode: 56440,
    },
    email: "octaviano.lopes@example.com",
    login: { username: "bluegoose857", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2013-12-01T06:38:40.479Z", age: 8 },
    phone: "(04) 0359-2510",
    picture: {
      large: "https://randomuser.me/api/portraits/men/2.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/2.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/2.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Gautam", last: "Nayak" },
    location: {
      street: { number: 611, name: "Mirza Ghalib St" },
      city: "Khammam",
      state: "Maharashtra",
      country: "India",
      postcode: 36323,
    },
    email: "gautam.nayak@example.com",
    login: { username: "whitewolf939", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2010-01-14T20:57:31.601Z", age: 12 },
    phone: "8780169770",
    picture: {
      large: "https://randomuser.me/api/portraits/men/58.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/58.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/58.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Edinaura", last: "Moreira" },
    location: {
      street: { number: 7295, name: "Rua Dom Pedro Ii " },
      city: "Aparecida de Goiânia",
      state: "Amapá",
      country: "Brazil",
      postcode: 29936,
    },
    email: "edinaura.moreira@example.com",
    login: { username: "blueleopard708", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2012-06-22T07:05:00.926Z", age: 10 },
    phone: "(98) 6326-1374",
    picture: {
      large: "https://randomuser.me/api/portraits/women/1.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/1.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/1.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Liva", last: "Larsen" },
    location: {
      street: { number: 6618, name: "Humlevej" },
      city: "Roedovre",
      state: "Danmark",
      country: "Denmark",
      postcode: 76033,
    },
    email: "liva.larsen@example.com",
    login: { username: "goldenbear742", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2012-12-12T19:56:03.770Z", age: 9 },
    phone: "40205698",
    picture: {
      large: "https://randomuser.me/api/portraits/women/53.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/53.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/53.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Patricia", last: "Olmos" },
    location: {
      street: { number: 1580, name: "Eje vial Sur Miramontes" },
      city: "San Salvador El Verde",
      state: "Quintana Roo",
      country: "Mexico",
      postcode: 87854,
    },
    email: "patricia.olmos@example.com",
    login: { username: "happygoose630", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2004-05-24T17:38:23.008Z", age: 18 },
    phone: "(604) 245 0772",
    picture: {
      large: "https://randomuser.me/api/portraits/women/96.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/96.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/96.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Álvaro", last: "Montero" },
    location: {
      street: { number: 1738, name: "Avenida de Castilla" },
      city: "Logroño",
      state: "Comunidad de Madrid",
      country: "Spain",
      postcode: 10568,
    },
    email: "alvaro.montero@example.com",
    login: { username: "goldenmeercat347", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2005-03-03T06:40:07.893Z", age: 17 },
    phone: "910-887-167",
    picture: {
      large: "https://randomuser.me/api/portraits/men/82.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/82.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/82.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Brielle", last: "Macdonald" },
    location: {
      street: { number: 1148, name: "Bay Ave" },
      city: "Kingston",
      state: "Saskatchewan",
      country: "Canada",
      postcode: 5556,
    },
    email: "brielle.macdonald@example.com",
    login: { username: "goldenbird395", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2017-04-27T14:03:42.384Z", age: 5 },
    phone: "W67 H16-2656",
    picture: {
      large: "https://randomuser.me/api/portraits/women/96.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/96.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/96.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "سینا", last: "كامياران" },
    location: {
      street: { number: 5804, name: "هلال احمر" },
      city: "گرگان",
      state: "کردستان",
      country: "Iran",
      postcode: 62258,
    },
    email: "syn.kmyrn@example.com",
    login: { username: "purpleostrich745", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2017-12-05T09:24:55.387Z", age: 4 },
    phone: "057-96732444",
    picture: {
      large: "https://randomuser.me/api/portraits/men/19.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/19.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/19.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Isaiah", last: "Harris" },
    location: {
      street: { number: 2388, name: "Lovers Ln" },
      city: "Cairns",
      state: "New South Wales",
      country: "Australia",
      postcode: 5307,
    },
    email: "isaiah.harris@example.com",
    login: { username: "silvergoose435", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2009-03-05T08:19:49.349Z", age: 13 },
    phone: "05-0728-9135",
    picture: {
      large: "https://randomuser.me/api/portraits/men/71.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/71.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/71.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Viivi", last: "Lahti" },
    location: {
      street: { number: 8360, name: "Aleksanterinkatu" },
      city: "Keuruu",
      state: "Central Ostrobothnia",
      country: "Finland",
      postcode: 40681,
    },
    email: "viivi.lahti@example.com",
    login: { username: "purpleleopard579", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2021-07-05T02:40:57.466Z", age: 1 },
    phone: "03-431-318",
    picture: {
      large: "https://randomuser.me/api/portraits/women/94.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/94.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/94.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Elias", last: "Madsen" },
    location: {
      street: { number: 984, name: "Kirkestræde" },
      city: "Sønder Stenderup",
      state: "Danmark",
      country: "Denmark",
      postcode: 46539,
    },
    email: "elias.madsen@example.com",
    login: { username: "whitezebra902", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2014-10-21T15:24:31.100Z", age: 7 },
    phone: "40626062",
    picture: {
      large: "https://randomuser.me/api/portraits/men/9.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/9.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/9.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Gina", last: "Storeide" },
    location: {
      street: { number: 9058, name: "Dronninghavnveien" },
      city: "Hovden",
      state: "Oppland",
      country: "Norway",
      postcode: "9022",
    },
    email: "gina.storeide@example.com",
    login: { username: "purplebutterfly895", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2002-09-02T00:19:33.976Z", age: 19 },
    phone: "21071008",
    picture: {
      large: "https://randomuser.me/api/portraits/women/55.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/55.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/55.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Russell", last: "Chapman" },
    location: {
      street: { number: 1456, name: "Ranchview Dr" },
      city: "Edison",
      state: "Vermont",
      country: "United States",
      postcode: 48405,
    },
    email: "russell.chapman@example.com",
    login: { username: "happyrabbit623", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2002-12-30T13:01:29.498Z", age: 19 },
    phone: "(273) 937-3340",
    picture: {
      large: "https://randomuser.me/api/portraits/men/93.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/93.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/93.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Simon", last: "Novak" },
    location: {
      street: { number: 4081, name: "Concession Road 6" },
      city: "Dorchester",
      state: "Northwest Territories",
      country: "Canada",
      postcode: 65550,
    },
    email: "simon.novak@example.com",
    login: { username: "ticklishcat842", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2018-06-03T11:50:56.156Z", age: 4 },
    phone: "D31 B73-9694",
    picture: {
      large: "https://randomuser.me/api/portraits/men/32.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/32.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/32.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Enni", last: "Pollari" },
    location: {
      street: { number: 3845, name: "Myllypuronkatu" },
      city: "Konnevesi",
      state: "Southern Savonia",
      country: "Finland",
      postcode: 74485,
    },
    email: "enni.pollari@example.com",
    login: { username: "whiteladybug549", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2018-02-22T23:54:33.327Z", age: 4 },
    phone: "04-759-583",
    picture: {
      large: "https://randomuser.me/api/portraits/women/77.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/77.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/77.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Floriaan", last: "Bens" },
    location: {
      street: { number: 8378, name: "Hemonylaan" },
      city: "Ommel",
      state: "Zuid-Holland",
      country: "Netherlands",
      postcode: 4449,
    },
    email: "floriaan.bens@example.com",
    login: { username: "goldenfrog305", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2006-12-07T03:56:25.075Z", age: 15 },
    phone: "(0856) 327522",
    picture: {
      large: "https://randomuser.me/api/portraits/men/39.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/39.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/39.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Bérénice", last: "Muller" },
    location: {
      street: { number: 3257, name: "Rue de Gerland" },
      city: "Asnières-sur-Seine",
      state: "Lozère",
      country: "France",
      postcode: 23947,
    },
    email: "berenice.muller@example.com",
    login: { username: "goldentiger289", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2011-08-20T23:33:55.010Z", age: 11 },
    phone: "05-59-08-56-74",
    picture: {
      large: "https://randomuser.me/api/portraits/women/45.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/45.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/45.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Elijah", last: "Nguyen" },
    location: {
      street: { number: 3705, name: "Lakeview St" },
      city: "Busselton",
      state: "Northern Territory",
      country: "Australia",
      postcode: 3264,
    },
    email: "elijah.nguyen@example.com",
    login: { username: "lazyladybug458", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2009-05-12T21:54:12.267Z", age: 13 },
    phone: "04-9207-4215",
    picture: {
      large: "https://randomuser.me/api/portraits/men/30.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/30.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/30.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Raúl", last: "Barros" },
    location: {
      street: { number: 9689, name: "Rua Treze " },
      city: "Bacabal",
      state: "Espírito Santo",
      country: "Brazil",
      postcode: 93637,
    },
    email: "raul.barros@example.com",
    login: { username: "goldenfrog333", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2016-01-05T06:23:38.408Z", age: 6 },
    phone: "(95) 2916-4841",
    picture: {
      large: "https://randomuser.me/api/portraits/men/18.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/18.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/18.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Natalie", last: "Moore" },
    location: {
      street: { number: 481, name: "Ahuriri Bypass" },
      city: "Lower Hutt",
      state: "Canterbury",
      country: "New Zealand",
      postcode: 54401,
    },
    email: "natalie.moore@example.com",
    login: { username: "happyduck411", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2020-03-14T01:24:44.445Z", age: 2 },
    phone: "(059)-523-4846",
    picture: {
      large: "https://randomuser.me/api/portraits/women/84.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/84.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/84.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Nelly", last: "Haro" },
    location: {
      street: { number: 469, name: "Privada Sur Arellano" },
      city: "San Pedro de Tututepec",
      state: "Baja California Sur",
      country: "Mexico",
      postcode: 75815,
    },
    email: "nelly.haro@example.com",
    login: { username: "yellowwolf365", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2008-02-22T02:27:45.343Z", age: 14 },
    phone: "(668) 271 0269",
    picture: {
      large: "https://randomuser.me/api/portraits/men/30.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/30.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/30.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Heine", last: "Nordvik" },
    location: {
      street: { number: 9998, name: "Lille Stensrud" },
      city: "Hauge",
      state: "Sør-Trøndelag",
      country: "Norway",
      postcode: 11178,
    },
    email: "heine.nordvik@example.com",
    login: { username: "beautifulpanda398", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2008-07-09T19:26:16.508Z", age: 14 },
    phone: "85479712",
    picture: {
      large: "https://randomuser.me/api/portraits/men/79.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/79.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/79.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "زهرا", last: "گلشن" },
    location: { street: { number: 3094, name: "فلسطین" }, city: "رشت", state: "یزد", country: "Iran", postcode: 24582 },
    email: "zhr.glshn@example.com",
    login: { username: "smallostrich436", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2006-01-18T05:14:28.029Z", age: 16 },
    phone: "038-93529635",
    picture: {
      large: "https://randomuser.me/api/portraits/women/34.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/34.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/34.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Alejandro", last: "Villa" },
    location: {
      street: { number: 1127, name: "Ampliación Sur Rael" },
      city: "Marfil",
      state: "Estado de Mexico",
      country: "Mexico",
      postcode: 86291,
    },
    email: "alejandro.villa@example.com",
    login: { username: "blackduck634", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2005-10-18T11:12:06.150Z", age: 16 },
    phone: "(630) 983 0976",
    picture: {
      large: "https://randomuser.me/api/portraits/men/31.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/31.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/31.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Zoran", last: "Meunier" },
    location: {
      street: { number: 1455, name: "Rue du Cardinal-Gerlier" },
      city: "Walenstadt",
      state: "Schaffhausen",
      country: "Switzerland",
      postcode: 9494,
    },
    email: "zoran.meunier@example.com",
    login: { username: "yellowelephant600", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2019-07-17T20:33:23.064Z", age: 3 },
    phone: "077 805 04 61",
    picture: {
      large: "https://randomuser.me/api/portraits/men/39.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/39.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/39.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Wade", last: "Kelley" },
    location: {
      street: { number: 753, name: "West Street" },
      city: "Liverpool",
      state: "County Tyrone",
      country: "United Kingdom",
      postcode: 5898,
    },
    email: "wade.kelley@example.com",
    login: { username: "happypeacock539", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2020-07-20T20:12:49.162Z", age: 2 },
    phone: "017684 36865",
    picture: {
      large: "https://randomuser.me/api/portraits/men/26.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/26.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/26.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Júlio", last: "Castro" },
    location: {
      street: { number: 2551, name: "Rua São Luiz " },
      city: "Apucarana",
      state: "Ceará",
      country: "Brazil",
      postcode: 50405,
    },
    email: "julio.castro@example.com",
    login: { username: "goldenmeercat533", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2022-02-24T17:51:49.278Z", age: 0 },
    phone: "(08) 5614-3474",
    picture: {
      large: "https://randomuser.me/api/portraits/men/37.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/37.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/37.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Ülkü", last: "Beşok" },
    location: {
      street: { number: 8618, name: "Tunalı Hilmi Cd" },
      city: "Tokat",
      state: "Edirne",
      country: "Turkey",
      postcode: 23666,
    },
    email: "ulku.besok@example.com",
    login: { username: "tinygorilla820", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2007-03-16T14:04:31.343Z", age: 15 },
    phone: "(490)-644-7639",
    picture: {
      large: "https://randomuser.me/api/portraits/women/87.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/87.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/87.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Sally", last: "Sutton" },
    location: {
      street: { number: 9809, name: "Ash Dr" },
      city: "Philadelphia",
      state: "New Jersey",
      country: "United States",
      postcode: 16421,
    },
    email: "sally.sutton@example.com",
    login: { username: "goldenpanda701", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2013-05-09T13:49:00.983Z", age: 9 },
    phone: "(361) 579-1979",
    picture: {
      large: "https://randomuser.me/api/portraits/women/76.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/76.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/76.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Hanna", last: "Perry" },
    location: {
      street: { number: 4885, name: "Queen Street" },
      city: "Oxford",
      state: "West Glamorgan",
      country: "United Kingdom",
      postcode: 58445,
    },
    email: "hanna.perry@example.com",
    login: { username: "organicbutterfly112", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2002-04-28T19:27:39.948Z", age: 20 },
    phone: "015394 31849",
    picture: {
      large: "https://randomuser.me/api/portraits/women/86.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/86.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/86.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Aiden", last: "Kowalski" },
    location: {
      street: { number: 9498, name: "22nd Ave" },
      city: "Hampton",
      state: "Ontario",
      country: "Canada",
      postcode: 55555,
    },
    email: "aiden.kowalski@example.com",
    login: { username: "crazygoose852", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2018-07-15T05:21:15.818Z", age: 4 },
    phone: "R64 F58-2848",
    picture: {
      large: "https://randomuser.me/api/portraits/men/86.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/86.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/86.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Peresvit", last: "Gorohovskiy" },
    location: {
      street: { number: 8553, name: "Brest-Litovske shose" },
      city: "Polonne",
      state: "Ivano-Frankivska",
      country: "Ukraine",
      postcode: 57940,
    },
    email: "peresvit.gorohovskiy@example.com",
    login: { username: "lazyelephant765", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2019-11-22T02:49:30.308Z", age: 2 },
    phone: "(099) I66-1971",
    picture: {
      large: "https://randomuser.me/api/portraits/men/58.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/58.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/58.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Mariah", last: "Van de Pol" },
    location: {
      street: { number: 3995, name: "Kreuleweg" },
      city: "Doorn",
      state: "Zeeland",
      country: "Netherlands",
      postcode: 97200,
    },
    email: "mariah.vandepol@example.com",
    login: { username: "happyfrog183", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2009-01-15T05:32:38.594Z", age: 13 },
    phone: "(0188) 411899",
    picture: {
      large: "https://randomuser.me/api/portraits/women/44.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/44.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/44.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Gaurav", last: "Belligatti" },
    location: {
      street: { number: 5515, name: "Gali Paranthe Wali" },
      city: "Nadiad",
      state: "Dadra and Nagar Haveli",
      country: "India",
      postcode: 32770,
    },
    email: "gaurav.belligatti@example.com",
    login: { username: "bigladybug539", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2016-07-26T06:05:53.687Z", age: 6 },
    phone: "8679512335",
    picture: {
      large: "https://randomuser.me/api/portraits/men/16.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/16.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/16.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Amber", last: "Wood" },
    location: {
      street: { number: 8132, name: "Durham Street" },
      city: "Whanganui",
      state: "Gisborne",
      country: "New Zealand",
      postcode: 85469,
    },
    email: "amber.wood@example.com",
    login: { username: "bluetiger410", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2013-04-19T08:25:58.809Z", age: 9 },
    phone: "(132)-597-5629",
    picture: {
      large: "https://randomuser.me/api/portraits/women/64.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/64.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/64.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Zilma", last: "Farias" },
    location: {
      street: { number: 101, name: "Rua São Jorge " },
      city: "Juazeiro do Norte",
      state: "Pernambuco",
      country: "Brazil",
      postcode: 30204,
    },
    email: "zilma.farias@example.com",
    login: { username: "orangepeacock655", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2003-12-25T16:56:22.111Z", age: 18 },
    phone: "(02) 5584-2965",
    picture: {
      large: "https://randomuser.me/api/portraits/women/77.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/77.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/77.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Itzel", last: "Valencia" },
    location: {
      street: { number: 1981, name: "Viaducto Quintana Roo" },
      city: "Pijijiapan",
      state: "Aguascalientes",
      country: "Mexico",
      postcode: 61482,
    },
    email: "itzel.valencia@example.com",
    login: { username: "heavymeercat931", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2016-03-22T09:27:22.967Z", age: 6 },
    phone: "(623) 307 5331",
    picture: {
      large: "https://randomuser.me/api/portraits/women/7.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/7.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/7.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Çetin", last: "Özbir" },
    location: {
      street: { number: 8389, name: "Bağdat Cd" },
      city: "Nevşehir",
      state: "Uşak",
      country: "Turkey",
      postcode: 18114,
    },
    email: "cetin.ozbir@example.com",
    login: { username: "brownbird341", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2010-02-07T23:59:15.408Z", age: 12 },
    phone: "(649)-500-3300",
    picture: {
      large: "https://randomuser.me/api/portraits/men/25.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/25.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/25.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Rosie", last: "Medina" },
    location: {
      street: { number: 7607, name: "The Crescent" },
      city: "Nottingham",
      state: "Cornwall",
      country: "United Kingdom",
      postcode: 11154,
    },
    email: "rosie.medina@example.com",
    login: { username: "orangesnake700", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2003-10-09T14:53:38.016Z", age: 18 },
    phone: "01064 13611",
    picture: {
      large: "https://randomuser.me/api/portraits/women/15.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/15.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/15.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Minouche", last: "Egas" },
    location: {
      street: { number: 9547, name: "Hoge Rij" },
      city: "Venlo",
      state: "Zuid-Holland",
      country: "Netherlands",
      postcode: 22425,
    },
    email: "minouche.egas@example.com",
    login: { username: "whitecat234", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2005-05-23T23:08:42.418Z", age: 17 },
    phone: "(029) 6051125",
    picture: {
      large: "https://randomuser.me/api/portraits/women/0.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/0.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/0.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Helmi", last: "Ojala" },
    location: {
      street: { number: 4931, name: "Otavalankatu" },
      city: "Kaskinen",
      state: "Tavastia Proper",
      country: "Finland",
      postcode: 30300,
    },
    email: "helmi.ojala@example.com",
    login: { username: "yellowgorilla540", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2012-04-09T05:03:26.512Z", age: 10 },
    phone: "04-229-541",
    picture: {
      large: "https://randomuser.me/api/portraits/women/22.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/22.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/22.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Andrijana", last: "Ivančević" },
    location: {
      street: { number: 3267, name: "Jasenova" },
      city: "Šid",
      state: "Central Banat",
      country: "Serbia",
      postcode: 49763,
    },
    email: "andrijana.ivancevic@example.com",
    login: { username: "crazygorilla632", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2019-09-04T09:49:41.091Z", age: 2 },
    phone: "021-2232-694",
    picture: {
      large: "https://randomuser.me/api/portraits/women/51.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/51.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/51.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Mason", last: "Sirko" },
    location: {
      street: { number: 5603, name: "36th Ave" },
      city: "Notre Dame de Lourdes",
      state: "Newfoundland and Labrador",
      country: "Canada",
      postcode: 2282,
    },
    email: "mason.sirko@example.com",
    login: { username: "silvermouse353", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2004-09-16T13:59:53.796Z", age: 17 },
    phone: "A68 S74-7632",
    picture: {
      large: "https://randomuser.me/api/portraits/men/23.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/23.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/23.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Nikolaj", last: "Christensen" },
    location: {
      street: { number: 7155, name: "Markskellet" },
      city: "København Sv",
      state: "Nordjylland",
      country: "Denmark",
      postcode: 89574,
    },
    email: "nikolaj.christensen@example.com",
    login: { username: "lazymeercat321", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2008-06-18T20:43:54.209Z", age: 14 },
    phone: "49496944",
    picture: {
      large: "https://randomuser.me/api/portraits/men/73.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/73.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/73.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Marisol", last: "Llamas" },
    location: {
      street: { number: 3725, name: "Diagonal Chile" },
      city: "Margaritas",
      state: "Yucatan",
      country: "Mexico",
      postcode: 69060,
    },
    email: "marisol.llamas@example.com",
    login: { username: "sadfrog170", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2004-08-03T21:00:23.432Z", age: 18 },
    phone: "(665) 203 5566",
    picture: {
      large: "https://randomuser.me/api/portraits/women/67.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/67.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/67.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Nicolas", last: "Gagné" },
    location: {
      street: { number: 1516, name: "Balmoral St" },
      city: "Delisle",
      state: "Yukon",
      country: "Canada",
      postcode: 3885,
    },
    email: "nicolas.gagne@example.com",
    login: { username: "greengoose765", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2011-02-04T11:29:36.945Z", age: 11 },
    phone: "P79 W85-6115",
    picture: {
      large: "https://randomuser.me/api/portraits/men/56.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/56.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/56.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Frida", last: "Dueñas" },
    location: {
      street: { number: 5687, name: "Corredor Vera" },
      city: "Nuevo Laredo",
      state: "Baja California",
      country: "Mexico",
      postcode: 16761,
    },
    email: "frida.duenas@example.com",
    login: { username: "silverwolf537", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2015-03-15T10:43:04.575Z", age: 7 },
    phone: "(636) 482 1181",
    picture: {
      large: "https://randomuser.me/api/portraits/women/73.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/73.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/73.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Hiba", last: "Sundseth" },
    location: {
      street: { number: 1618, name: "Bentsebrugata" },
      city: "Hovin",
      state: "Nord-Trøndelag",
      country: "Norway",
      postcode: "4635",
    },
    email: "hiba.sundseth@example.com",
    login: { username: "bigleopard781", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2017-10-20T03:19:10.715Z", age: 4 },
    phone: "78767338",
    picture: {
      large: "https://randomuser.me/api/portraits/women/60.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/60.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/60.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Louisa", last: "Menard" },
    location: {
      street: { number: 4601, name: "Rue Abel-Hovelacque" },
      city: "Strasbourg",
      state: "Lozère",
      country: "France",
      postcode: 84812,
    },
    email: "louisa.menard@example.com",
    login: { username: "crazycat757", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2017-05-19T12:18:04.713Z", age: 5 },
    phone: "02-71-45-07-17",
    picture: {
      large: "https://randomuser.me/api/portraits/women/4.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/4.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/4.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Živorad", last: "Mitrović" },
    location: {
      street: { number: 3227, name: "Bobska" },
      city: "Kraljevo",
      state: "Kosovo-Pomoravlje",
      country: "Serbia",
      postcode: 68861,
    },
    email: "zivorad.mitrovic@example.com",
    login: { username: "goldenrabbit312", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2004-07-17T23:52:31.157Z", age: 18 },
    phone: "034-1912-445",
    picture: {
      large: "https://randomuser.me/api/portraits/men/56.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/56.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/56.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Semih", last: "Erdem" },
    location: {
      street: { number: 2466, name: "Blekerdijk" },
      city: "Egmondermeer",
      state: "Noord-Holland",
      country: "Netherlands",
      postcode: 1920,
    },
    email: "semih.erdem@example.com",
    login: { username: "goldenpanda628", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2007-05-12T19:37:13.339Z", age: 15 },
    phone: "(0223) 131654",
    picture: {
      large: "https://randomuser.me/api/portraits/men/53.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/53.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/53.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Aynur", last: "Brendel" },
    location: {
      street: { number: 614, name: "Dorfstraße" },
      city: "Freyung-Grafenau",
      state: "Baden-Württemberg",
      country: "Germany",
      postcode: 66733,
    },
    email: "aynur.brendel@example.com",
    login: { username: "angrytiger652", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2012-06-15T01:06:10.706Z", age: 10 },
    phone: "0527-8437641",
    picture: {
      large: "https://randomuser.me/api/portraits/women/39.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/39.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/39.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Sherri", last: "Perkins" },
    location: {
      street: { number: 4230, name: "Dane St" },
      city: "Hobart",
      state: "Western Australia",
      country: "Australia",
      postcode: 6990,
    },
    email: "sherri.perkins@example.com",
    login: { username: "sadlion622", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2008-06-15T11:55:15.308Z", age: 14 },
    phone: "04-9809-2570",
    picture: {
      large: "https://randomuser.me/api/portraits/women/35.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/35.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/35.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Lucy", last: "Noel" },
    location: {
      street: { number: 6007, name: "Avenue Debrousse" },
      city: "Nancy",
      state: "Yvelines",
      country: "France",
      postcode: 57043,
    },
    email: "lucy.noel@example.com",
    login: { username: "redrabbit425", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2015-07-12T23:54:32.222Z", age: 7 },
    phone: "03-94-72-95-40",
    picture: {
      large: "https://randomuser.me/api/portraits/women/69.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/69.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/69.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "بنیامین", last: "نكو نظر" },
    location: {
      street: { number: 5000, name: "مصطفی خمینی" },
      city: "ساوه",
      state: "قم",
      country: "Iran",
      postcode: 40107,
    },
    email: "bnymyn.nkwnzr@example.com",
    login: { username: "redbird249", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2011-06-14T10:04:08.501Z", age: 11 },
    phone: "049-65256892",
    picture: {
      large: "https://randomuser.me/api/portraits/men/73.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/73.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/73.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Luukas", last: "Mattila" },
    location: {
      street: { number: 676, name: "Pyynikintie" },
      city: "Toholampi",
      state: "Northern Savonia",
      country: "Finland",
      postcode: 22166,
    },
    email: "luukas.mattila@example.com",
    login: { username: "ticklishbutterfly377", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2008-08-17T20:03:03.392Z", age: 14 },
    phone: "08-847-918",
    picture: {
      large: "https://randomuser.me/api/portraits/men/41.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/41.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/41.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Edward", last: "Kuhn" },
    location: {
      street: { number: 7267, name: "Miller Ave" },
      city: "Nampa",
      state: "Iowa",
      country: "United States",
      postcode: 61580,
    },
    email: "edward.kuhn@example.com",
    login: { username: "silverbear826", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2002-12-31T18:18:48.197Z", age: 19 },
    phone: "(912) 221-6274",
    picture: {
      large: "https://randomuser.me/api/portraits/men/93.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/93.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/93.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Angie", last: "Riley" },
    location: {
      street: { number: 1863, name: "South Street" },
      city: "Newbridge",
      state: "Cavan",
      country: "Ireland",
      postcode: 57286,
    },
    email: "angie.riley@example.com",
    login: { username: "orangerabbit374", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2006-01-18T08:22:19.367Z", age: 16 },
    phone: "011-789-6720",
    picture: {
      large: "https://randomuser.me/api/portraits/women/10.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/10.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/10.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Charles", last: "Pena" },
    location: {
      street: { number: 9926, name: "Walnut Hill Ln" },
      city: "Sunshine Coast",
      state: "Tasmania",
      country: "Australia",
      postcode: 9549,
    },
    email: "charles.pena@example.com",
    login: { username: "lazygorilla959", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2007-01-23T04:20:37.531Z", age: 15 },
    phone: "01-9655-1967",
    picture: {
      large: "https://randomuser.me/api/portraits/men/70.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/70.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/70.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Rayaan", last: "Padmanabha" },
    location: {
      street: { number: 6229, name: "Ranganathan St" },
      city: "Bardhaman",
      state: "Daman and Diu",
      country: "India",
      postcode: 44558,
    },
    email: "rayaan.padmanabha@example.com",
    login: { username: "brownbird322", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2022-04-30T23:02:11.030Z", age: 0 },
    phone: "8411521563",
    picture: {
      large: "https://randomuser.me/api/portraits/men/93.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/93.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/93.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "male",
    name: { first: "Peresvit", last: "Svitlickiy" },
    location: {
      street: { number: 4444, name: "Batova" },
      city: "Fastiv",
      state: "Kiyivska",
      country: "Ukraine",
      postcode: 94251,
    },
    email: "peresvit.svitlickiy@example.com",
    login: { username: "lazyswan867", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2006-10-13T15:50:51.973Z", age: 15 },
    phone: "(096) J39-8839",
    picture: {
      large: "https://randomuser.me/api/portraits/men/54.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/54.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/54.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Layla", last: "Thomas" },
    location: {
      street: { number: 1039, name: "Pages Road" },
      city: "Christchurch",
      state: "Canterbury",
      country: "New Zealand",
      postcode: 15583,
    },
    email: "layla.thomas@example.com",
    login: { username: "purplepeacock586", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2008-06-12T11:51:46.437Z", age: 14 },
    phone: "(597)-315-3020",
    picture: {
      large: "https://randomuser.me/api/portraits/women/48.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/48.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/48.jpg",
    },
    isAdmin: false,
  },
  {
    gender: "female",
    name: { first: "Amelia", last: "Lambert" },
    location: {
      street: { number: 7292, name: "Rue D'Abbeville" },
      city: "Avignon",
      state: "Haute-Vienne",
      country: "France",
      postcode: 11007,
    },
    email: "amelia.lambert@example.com",
    login: { username: "happypanda313", password: bcrypt.hashSync("123456", 10) },
    registered: { date: "2018-10-04T13:15:23.348Z", age: 3 },
    phone: "04-04-02-43-03",
    picture: {
      large: "https://randomuser.me/api/portraits/women/78.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/78.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/78.jpg",
    },
    isAdmin: false,
  },
];
